apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-text-summarization
  namespace: easy-kart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app-text-summarization
  template:
    metadata:
      labels:
        app: ml-app-text-summarization
    spec:
      containers:
      - name: ml-app-text-summarization
        image: pdesaidocker/ml-app-text-summarization:{{imageTag}}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-app-text-summarization-service
  namespace: easy-kart
spec:
  selector:
    app: ml-app-text-summarization 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 5000 
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-app-text-summarization
  namespace: easy-kart
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /review-summary
    nginx.ingress.kubernetes.io/use-regex: 'true'
    ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: easy-kart.centralindia.cloudapp.azure.com
      http:
        paths:
          - path: /summary
            pathType: ImplementationSpecific
            backend:
              service:
                name: ml-app-text-summarization-service
                port:
                  number: 80
---